"""Provider-agnostic abstract base interface for LLM providers."""

from abc import ABC, abstractmethod
from typing import Any, Literal

from pydantic import BaseModel, Field


class LLMMessage(BaseModel):
    """Single message in a conversational LLM exchange."""

    role: Literal["system", "user", "assistant", "tool"] = Field(...)
    content: str = Field(...)


class LLMResponse(BaseModel):
    """Standardized response container from LLM generation."""

    content: str = Field(..., description="Raw text generated by the model")
    model: str = Field(..., description="Model identifier used for generation")
    usage: dict[str, int] = Field(
        default_factory=dict, description="Token usage stats if available"
    )
    raw_response: dict[str, Any] | None = Field(
        default=None, description="Optional raw provider payload"
    )


class BaseLLMProvider(ABC):
    """Abstract interface that all LLM adapters must implement."""

    @abstractmethod
    async def generate_response(
        self,
        messages: list[LLMMessage],
        temperature: float = 0.2,
        max_tokens: int = 2048,
        timeout: float = 15.0,
    ) -> LLMResponse:
        """Generates a text completion from a list of structured messages."""
        pass
