import React, { useEffect, useState } from 'react';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { EmptyState } from '@/components/ui/empty-state';
import { Skeleton } from '@/components/ui/skeleton';
import { api } from '@/lib/api-client';
import { QuoteDetail, QuoteItemDetail } from '@/types/portal';
import { formatPaiseToINR, formatRelativeTime } from '@/lib/utils';
import { FileSpreadsheet, Clock } from 'lucide-react';

export const QuotesPage: React.FC = () => {
  const [quotes, setQuotes] = useState<QuoteDetail[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchQuotes = async () => {
      try {
        const data = await api.listQuotes();
        setQuotes(data);
        setError(null);
      } catch (err: unknown) {
        setError(err instanceof Error ? err.message : 'Unable to load quotes.');
      } finally {
        setIsLoading(false);
      }
    };
    fetchQuotes();
  }, []);

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'ACCEPTED': return <Badge variant="success">ACCEPTED</Badge>;
      case 'PROPOSED': return <Badge variant="default">PROPOSED</Badge>;
      case 'NEGOTIATING': return <Badge variant="warning">NEGOTIATING</Badge>;
      case 'REJECTED': return <Badge variant="destructive">REJECTED</Badge>;
      default: return <Badge variant="secondary">{status}</Badge>;
    }
  };

  const displayStatus = (quote: QuoteDetail) =>
    ['PROPOSED', 'NEGOTIATING'].includes(quote.status) && new Date(quote.expires_at).getTime() <= Date.now()
      ? 'EXPIRED'
      : quote.status;

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold tracking-tight">Price Quotes & Binding Offers</h2>
        <p className="text-xs text-muted-foreground mt-0.5">
          Binding commercial proposals issued by the Deterministic Policy Engine.
        </p>
      </div>

      {isLoading ? (
        <div className="space-y-3">
          {[1, 2, 3].map((i) => <Skeleton key={i} className="h-20 w-full" />)}
        </div>
      ) : error ? (
        <EmptyState icon={<FileSpreadsheet className="h-10 w-10" />} title="Quotes unavailable" description={error} />
      ) : quotes.length === 0 ? (
        <EmptyState
          icon={<FileSpreadsheet className="h-10 w-10" />}
          title="No quotes recorded"
          description="Price quotes generated by AI buyers or agent negotiation sessions will appear here."
        />
      ) : (
        <div className="space-y-4">
          {quotes.map((q) => (
            <Card key={q.id} className="border-border bg-card/80">
              <CardHeader className="pb-3">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs text-muted-foreground">{q.id.slice(0, 8)}...</span>
                    {getStatusBadge(displayStatus(q))}
                  </div>
                  <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Clock className="h-3.5 w-3.5" />
                      Created {formatRelativeTime(q.created_at)}
                    </span>
                    <span className="font-bold text-foreground text-sm">{formatPaiseToINR(q.total_paise)}</span>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="border-t border-border pt-3 text-xs space-y-2">
                <div className="flex justify-between text-muted-foreground">
                  <span>Subtotal: {formatPaiseToINR(q.subtotal_paise)}</span>
                  <span>Discount: {formatPaiseToINR(q.discount_paise)}</span>
                  <span>Shipping: {formatPaiseToINR(q.shipping_paise)}</span>
                </div>
                {q.discount_reason && (
                  <p className="text-[11px] text-primary italic">Reason: {q.discount_reason}</p>
                )}
                <div className="mt-2 space-y-1 bg-muted/20 p-2 rounded">
                  {q.items.map((it: QuoteItemDetail, idx: number) => (
                    <div key={idx} className="flex justify-between text-[11px]">
                      <span>{it.quantity}x {it.title} ({it.sku})</span>
                      <span className="font-mono">{formatPaiseToINR(it.total_price_paise)}</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};
